<?php
/**
 * Template helpers: icons, images, fields, links and safe output.
 *
 * @package Estatein
 */

defined( 'ABSPATH' ) || exit;

/**
 * URL of a file in the theme's assets folder.
 *
 * @param string $path Path relative to /assets.
 * @return string
 */
function estatein_asset( $path ) {
	return ESTATEIN_URI . '/assets/' . ltrim( $path, '/' );
}

/**
 * Inline <svg> that references a symbol in the icon sprite.
 *
 * @param string $name  Symbol id (see src/icons in the repository).
 * @param string $class Extra classes.
 * @return string
 */
function estatein_icon( $name, $class = '' ) {
	return sprintf(
		'<svg class="%1$s" aria-hidden="true"><use href="%2$s"></use></svg>',
		esc_attr( trim( 'icon ' . $class ) ),
		esc_url( estatein_asset( 'icons/sprite.svg' ) ) . '#' . esc_attr( $name )
	);
}

/**
 * Sprite symbol with an exact class list (no "icon" base class), e.g. the
 * sparkles above section titles and the logo.
 *
 * @param string $name  Symbol id.
 * @param string $class Classes.
 * @return string
 */
function estatein_symbol( $name, $class ) {
	return sprintf(
		'<svg class="%1$s" aria-hidden="true"><use href="%2$s"></use></svg>',
		esc_attr( $class ),
		esc_url( estatein_asset( 'icons/sprite.svg' ) ) . '#' . esc_attr( $name )
	);
}

/**
 * URL of the Terms & Conditions page (falls back to the privacy policy).
 *
 * @return string
 */
function estatein_terms_url() {
	$page = get_page_by_path( 'terms-and-conditions' );
	if ( $page ) {
		return get_permalink( $page );
	}
	return get_privacy_policy_url() ? get_privacy_policy_url() : home_url( '/' );
}

/**
 * URL of the Privacy Policy page (falls back to the terms page).
 *
 * @return string
 */
function estatein_privacy_url() {
	return get_privacy_policy_url() ? get_privacy_policy_url() : estatein_terms_url();
}

/**
 * Sizes/widths of the theme's bundled WebP images (generated by tools/optimize-images.js).
 *
 * @return array
 */
function estatein_image_manifest() {
	static $manifest = null;
	if ( null === $manifest ) {
		$file     = ESTATEIN_DIR . '/assets/images/manifest.json';
		$manifest = file_exists( $file ) ? (array) json_decode( (string) file_get_contents( $file ), true ) : array(); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	}
	return $manifest;
}

/**
 * <img> for one of the theme's bundled images, with the same srcset as the static build.
 *
 * @param string $name  Image name in the manifest (e.g. "hero-buildings").
 * @param array  $attrs Attributes: class, alt, width, height, sizes, src_width, loading, fetchpriority.
 * @return string
 */
function estatein_theme_image( $name, $attrs = array() ) {
	$manifest = estatein_image_manifest();
	if ( empty( $manifest[ $name ] ) ) {
		return '';
	}
	$widths = $manifest[ $name ]['widths'];
	$srcset = array();
	foreach ( $widths as $w ) {
		$srcset[] = estatein_asset( "images/{$name}-{$w}.webp" ) . " {$w}w";
	}
	$src_width = isset( $attrs['src_width'] ) && in_array( (int) $attrs['src_width'], $widths, true ) ? (int) $attrs['src_width'] : end( $widths );
	unset( $attrs['src_width'] );

	$attrs = wp_parse_args(
		$attrs,
		array(
			'src'      => estatein_asset( "images/{$name}-{$src_width}.webp" ),
			'srcset'   => implode( ', ', $srcset ),
			'alt'      => '',
			'loading'  => 'lazy',
			'decoding' => 'async',
		)
	);
	if ( isset( $attrs['loading'] ) && 'eager' === $attrs['loading'] ) {
		unset( $attrs['loading'], $attrs['decoding'] );
	}

	$html = '<img';
	foreach ( $attrs as $key => $value ) {
		$html .= sprintf( ' %s="%s"', esc_attr( $key ), 'src' === $key ? esc_url( $value ) : esc_attr( $value ) );
	}
	return $html . '>';
}

/**
 * Image from the media library (attachment) or, when empty, a bundled theme image.
 *
 * @param int|string $attachment_id Attachment ID (may be empty).
 * @param string     $fallback      Theme image name used when there is no attachment.
 * @param array      $attrs         Attributes (class, alt, sizes, width, height …).
 * @param string     $size          Registered image size for attachments.
 * @return string
 */
function estatein_image( $attachment_id, $fallback, $attrs = array(), $size = 'large' ) {
	if ( $attachment_id && wp_attachment_is_image( (int) $attachment_id ) ) {
		$attr = $attrs;
		unset( $attr['src_width'], $attr['width'], $attr['height'] );
		if ( empty( $attr['alt'] ) ) {
			unset( $attr['alt'] ); // Let WordPress use the attachment's alt text.
		}
		return wp_get_attachment_image( (int) $attachment_id, $size, false, $attr );
	}
	return $fallback ? estatein_theme_image( $fallback, $attrs ) : '';
}

/**
 * Read a custom field (ACF when active, plain post meta otherwise),
 * falling back to the design default from inc/content.php.
 *
 * @param string   $key     Field name.
 * @param int|null $post_id Post ID (defaults to the current post).
 * @return mixed
 */
function estatein_field( $key, $post_id = null ) {
	$post_id = $post_id ? $post_id : get_the_ID();
	$value   = null;

	if ( function_exists( 'get_field' ) ) {
		$value = get_field( $key, $post_id, false );
	} elseif ( $post_id ) {
		$value = get_post_meta( $post_id, $key, true );
	}

	if ( null === $value || '' === $value || false === $value ) {
		$value = estatein_default( $key );
	}
	return $value;
}

/**
 * Field value as escaped plain text.
 *
 * @param string   $key     Field name.
 * @param int|null $post_id Post ID.
 */
function estatein_the_text( $key, $post_id = null ) {
	echo esc_html( (string) estatein_field( $key, $post_id ) );
}

/**
 * Field value that may contain the small amount of inline markup used by the
 * design copy (e.g. <span class="hide-mobile"> for breakpoint-specific text).
 *
 * @param string   $key     Field name.
 * @param int|null $post_id Post ID.
 */
function estatein_the_html( $key, $post_id = null ) {
	echo estatein_kses( (string) estatein_field( $key, $post_id ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- sanitised by estatein_kses().
}

/**
 * Allow only inline formatting tags in editable copy.
 *
 * @param string $html Raw HTML.
 * @return string
 */
function estatein_kses( $html ) {
	return wp_kses(
		$html,
		array(
			'span'   => array( 'class' => true ),
			'a'      => array( 'href' => true, 'class' => true, 'target' => true, 'rel' => true ),
			'strong' => array(),
			'em'     => array(),
			'br'     => array(),
		)
	);
}

/**
 * Theme setting (Customizer) with the design default.
 *
 * @param string $key Setting name.
 * @return mixed
 */
function estatein_option( $key ) {
	return get_theme_mod( $key, estatein_default( $key ) );
}

/**
 * Permalink of the first published page that uses a page template.
 *
 * @param string $template Template slug: about, properties, services or contact.
 * @param string $anchor   Optional #fragment.
 * @return string
 */
function estatein_page_url( $template, $anchor = '' ) {
	static $cache = array();
	if ( ! isset( $cache[ $template ] ) ) {
		$pages              = get_pages(
			array(
				'meta_key'   => '_wp_page_template', // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_key
				'meta_value' => 'page-templates/' . $template . '.php', // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_value
				'number'     => 1,
			)
		);
		$cache[ $template ] = $pages ? get_permalink( $pages[0] ) : home_url( '/' . $template . '/' );
	}
	return $cache[ $template ] . ( $anchor ? '#' . $anchor : '' );
}

/**
 * Turn a theme-relative link from inc/content.php ("@about#our-team", "@properties")
 * into a real URL; anything else is returned unchanged.
 *
 * @param string $link Link value.
 * @return string
 */
function estatein_link( $link ) {
	if ( 0 === strpos( (string) $link, '@' ) ) {
		$parts = explode( '#', substr( $link, 1 ), 2 );
		if ( 'home' === $parts[0] ) {
			return home_url( '/' ) . ( isset( $parts[1] ) ? '#' . $parts[1] : '' );
		}
		if ( 'testimonials' === $parts[0] || 'faqs' === $parts[0] ) {
			$type = 'testimonials' === $parts[0] ? 'testimonial' : 'faq';
			return (string) get_post_type_archive_link( $type ) . ( isset( $parts[1] ) ? '#' . $parts[1] : '' );
		}
		return estatein_page_url( $parts[0], isset( $parts[1] ) ? $parts[1] : '' );
	}
	return (string) $link;
}

/**
 * Format a number as the design shows prices ("$1,250,000").
 *
 * @param mixed $value Number or text.
 * @return string
 */
function estatein_price( $value ) {
	if ( is_numeric( $value ) ) {
		return '$' . number_format_i18n( (float) $value );
	}
	return (string) $value;
}

/**
 * Two-digit counter used by the carousels and spec values ("04").
 *
 * @param int $n Number.
 * @return string
 */
function estatein_pad( $n ) {
	return str_pad( (string) (int) $n, 2, '0', STR_PAD_LEFT );
}
